name: .NET Build with no tests

env:
  CONFIGURATION: Release
  MAJOR_RELEASE: 1
  PACKAGE_SUFFIX: development

on:
  workflow_call:
    inputs:
        artifact_name:
          required: true
          type: string

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Authenticate to Github packages
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/github-actions-training/index.json"

    # This step assumed the solution has been set up with nuget package locking.
    # See https://blog.soenneker.com/how-to-setup-nuget-caching-in-azure-devops-8d94c57b5321 for instructions.
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: Package
      run: |
        dotnet publish -c Release --output artifacts --no-restore --no-build

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: artifacts

    - uses: actions/upload-artifact@v3
      with:
        name: infrastructure
        path: infrastructure